# Generated by Django 3.1.2 on 2020-10-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
        ('ingredients', '0001_initial'),
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='ingredients',
            field=models.ManyToManyField(through='recipes.Recipe', to='ingredients.Ingredient'),
        ),
    ]
