# Generated by Django 3.1.2 on 2020-10-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_drink_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
