# Generated by Django 3.1.2 on 2020-10-30 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0003_auto_20201029_1745'),
        ('ingredients', '0001_initial'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together={('drink', 'ingredient', 'amount')},
        ),
    ]
